# Generated by Django 2.0.3 on 2018-03-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicHome', '0002_auto_20180326_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='thumbnail',
        ),
    ]
