# Generated by Django 2.0.3 on 2018-03-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicHome', '0003_remove_song_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
