# Generated by Django 2.0.3 on 2018-04-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicHome', '0006_auto_20180406_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='gnere',
            field=models.CharField(default='', max_length=50),
        ),
    ]
