# Generated by Django 2.0.3 on 2018-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicHome', '0008_auto_20180408_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
